on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      content: read
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: make bundle
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ""
          entrypoint: "./bundle.js"
